# Generated by Django 3.2.9 on 2021-12-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('IOS', 'IOS'), ('ANDROID', 'ANDROID')], default='ANDROID', max_length=7)),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField()),
                ('installs', models.PositiveIntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('impressions', models.PositiveBigIntegerField()),
            ],
        ),
    ]
