# Generated by Django 3.2.9 on 2021-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemeasure',
            name='os',
            field=models.CharField(choices=[('ios', 'ios'), ('android', 'android')], default='android', max_length=7),
        ),
    ]
